print("este es un nuevo archivo :)")
x=int(input("ingresa un numero:"))
y=int(input("ingresa otro numero:"))
print(f"la suma total de {x} y {y} es: {x+y}")
print(f"la resta total de {x} y {y} es: {x-y}")
print(f"la multiplicacion total de {x} y {y} es: {x*y}")
print(f"la division total de {x} y {y} es: {x/y}")